Repository wdavidcalsin/my-page, pull requests merged in 2020-11, with the labels that each got.

#22 fix: ✍️ Purge gh actions
  .eslintignore
  .github/workflows/ci-workflow.yml
  changelog.config.js
  package.json
Labels: bug, enhancement, help wanted

#23 docs: ✏️ udpated the readme file
  README.md
Labels: documentation

#33 Update README.md
  README.md
Labels: documentation

#41 Scroll top for header
  package-lock.json
  package.json
  src/components/Header/Header.tsx
  src/styles/components/Header/Header.scss
Labels: enhancement
