Repository wdavidcalsin/my-page, pull requests merged in 2020-10, with the labels that each got.

#1 chore: 🤖 configure
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/workflows/ci-workflow.yml
  .prettierignore
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  public/manifest.json
  src/App.test.js
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Header/Module.ts
  src/components/Header/Styled.tsx
  src/components/Header/Styled1.tsx
  src/components/Section/Section.tsx
  src/components/Section/Styled.tsx
  src/components/Section/Styled1.tsx
  src/index.tsx
  src/serviceWorker.js
  tsconfig.json
  yarn.lock
Labels: enhancement, good first issue

#2 fixes
  .nvmrc
Labels: bug, enhancement

#5 add scss and remove styled-components
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Header/Module.ts
  src/components/Header/Styled.tsx
  src/components/Header/elements.tsx
  src/components/Section/Section.tsx
  src/components/Section/Styled.tsx
  src/components/Section/Styled1.tsx
  src/styles/components/Header/Header.scss
  src/styles/components/Section/Section.scss
  src/styles/components/componenst.scss
  src/styles/global/global.scss
  src/styles/main.scss
Labels: bug, enhancement, help wanted

#6 refactor: 💡 update-nvm-node-version
  .nvmrc
Labels: enhancement, help wanted

#7 feat: Create scripts
  package.json
  scripts/fetch.sh
  src/App.test.tsx
  src/serviceWorker.ts
  src/setupTests.ts
Labels: bug, enhancement, help wanted

#8 refactor: 💡 active-pwa
  src/index.tsx
Labels: bug, enhancement

#12 foot add abd twitter widget in section
  package-lock.json
  package.json
  src/App.tsx
  src/components/Footer/Footer.tsx
  src/components/Section/Section.tsx
  src/styles/components/Footer/Footer.scss
  src/styles/components/Header/Header.scss
  src/styles/components/Section/Section.scss
  src/styles/components/componenst.scss
  src/styles/main.scss
Labels: enhancement, help wanted

#13 refactor: 💡 router integration
  package.json
  src/App.tsx
  src/components/Header/Header.tsx
  src/components/Section/Section.tsx
  src/components/index.tsx
  src/layouts/index.tsx
  src/pages/home.tsx
  src/pages/index.tsx
  src/pages/me.tsx
  src/styles/components/Header/Header.scss
  src/styles/components/Section/Section.scss
  yarn.lock
Labels: duplicate, enhancement
